### PR TITLE
some installfest tweaks after tonight's installfest

### PR DESCRIPTION
**Pull request by maxjacobson**
thx to @acatighera for helping write these changes!

Not sure if the css thing is appropriate, just wanted to emphasize this point a bit 😬

### CODE REVIEW

**Comment by maxjacobson** [comment]
I think there's one more heroku open to update actually

**Comment by maxjacobson** [comment]
OK made the last updates I wanted to make, this is ready for a review @qiheme

**Comment by qiheme** [comment]
@maxjacobson looks like Github does the auto deploy link for us!!! Huzzah!!

**Comment by qiheme** [comment]
Thanks @maxjacobson and  @acatighera!! Merged!

**Pull request merged**
